theme: jekyll-theme-hacker
title: How to Setup Github for Beginner💻
author: Miftah Ahmad Choiri
description: Create a GitHub repo named miftah-ahmad-choiri.github.io, push Jekyll files, enable GitHub Pages in settings, and visit https://miftah-ahmad-choiri.github.io